M48
; DRILL file {KiCad 9.0.5} date 2026-05-05T20:00:00-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-05T20:00:00-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
%
G90
G05
T1
X133.0Y-79.313
X138.78Y-79.313
T2
X127.0Y-127.0
X165.1Y-76.2
M30
